### ISSUE TITLE
Keyboard Macros

### ISSUE THREAD

**Issue by keyboardbuldier** [dhowland/EasyAVR#108]
When I try to write a macro with the unusual character ä, the program returns an error when I try to build and reprogram.

**Comment by dhowland** [comment]
Yes I'm afraid the project has no support for internationalization support.  I'm in the US and I basically programmed a 1:1 mapping of ascii codes to scancodes.  It doesn't understand unicode or other keyboard layouts.

That being said, there may be a relatively simple fix for this by using hex codes.  If you post the error message, I can take a look.

**Comment by keyboardbuldier** [comment]
Same isue here "unicode macro support"

**Comment by dhowland** [comment]
Oh yeah, #35.  I really should do something about that.  At a minimum it shouldn't crash when unsupported characters are entered.
