### ISSUE TITLE
[Fetures] need a huge matrix large than 7*24 or 8*18

### ISSUE THREAD

**Issue by jindaxia** [dhowland/EasyAVR#36]
I have a **[Reuters D3D-KP](http://www.ebay.com/itm/Reuters-D3D-KP-Trading-Keypad-Keyboard-10-11-3010-/171178300447)** keyboard, now i want to resurvell it with the teensy2.0.
that has 11 rows and 14cols in its phisical circult . so i want to build an firmware support 15*15 or more .
I will send a PR later

**Comment by dhowland** [comment]
You're going to run out of memory.

**Comment by jindaxia** [comment]
@dhowland haha，you are right， I tried to build that and as you said out of memory，
but when I build the 11*14 ， it's just use the full memory.  
so i will just use this firmware for myself before i find a better way to support dynamic matrix size build.

**Comment by dhowland** [comment]
This issue has been idle for a long time.  closing
