### ISSUE TITLE
Debugging on device

### ISSUE THREAD

**Issue by GeeWizWow** [dhowland/EasyAVR#38]
Hi @dhowland 

Any chance you could give some pointers as to the necessary steps for debugging the firmware code?
I've done quite a bit of reading and can't seem to figure out if external hardware is needed or not...

Cheers

**Comment by dhowland** [comment]
External hardware is needed, and you need to be using a board that has the debug headers on it.  Usually JTAG

**Comment by dhowland** [comment]
Also, there are some debug features in the firmware itself, as long as you can get it running.
