### ISSUE TITLE
Locking key issue

### ISSUE THREAD

**Issue by pimaxc** [dhowland/EasyAVR#45]
Specific hardware setup GH60 Satan function key mapped to lockable.  The key was double tapped and  locked to second layer, however I could not unlock by pressing function key again.

**Comment by dhowland** [comment]
I think there may be a misunderstanding of how the firmware works.  It tracks assigned scancodes, not buttons.

So if you have a lockable FN2, for example, you have to press FN2 again to unlock it.  If you don't have FN2 mapped to the same key on to Layer2, then you aren't going to be able to unlock it.  The button does nothing unless it is mapped to the right scancode.

**Comment by pimaxc** [comment]
ah that's probably my problem thank you
