### ISSUE TITLE
Feature request support for physically locking key

### ISSUE THREAD

**Issue by pimaxc** [dhowland/EasyAVR#46]
Support for caps lock num lock etc with cherry MX lock.  As the current firmware works the most effective way to use it is by mapping the caps lock as a shift key.

**Comment by dhowland** [comment]
I have a keyboard right now (Sigma) with three MXlock keys.  They work fine.  To use them, you have to use the special LOCKING scancodes.

**Comment by pimaxc** [comment]
Did not see that scancode.  Thank you.
