### ISSUE TITLE
Request: two key support 

### ISSUE THREAD

**Issue by pimaxc** [dhowland/EasyAVR#50]
https://mehkee.com/products/macropad-2-switch-pcb?variant=45125555663

**Comment by dhowland** [comment]
Do you have a pinout diagram or anything else that describes the matrix?

**Comment by pimaxc** [comment]
Switch pins are 2 and 3 source code for their arduino sketch is here. https://github.com/di0ib/Misc/blob/master/2pack/2pack.ino

**Comment by tahuds** [comment]
This would be awesome.

**Comment by dhowland** [comment]
This is going to be the last board I do by myself.  Going forward I'm going to require that people at least try to follow the "Supporting custom boards" section of the README.

I have added initial support for the 2key but it requires testing.  Please give it a shot and let me know if it works.  Thanks

**Comment by tahuds** [comment]
Thank you!  I'm guessing from your picture you don't have a lot of free time and EasyKeyMapper has made a lot of people's lives better. Sorry for bothering you.

**Comment by dhowland** [comment]
No need to be sorry, it's cool.  What would really help is some testing.  I don't own the hardware, so I'm not able to do it myself.  Thanks

**Comment by tahuds** [comment]
I've been waiting on getting the pro micro board for the pcb. Once they are
in stock I'll let you know! :)

**Comment by pimaxc** [comment]
I'm trying but looks like I need to flash a new boot loader to get it to recognize and I don't have the hardware for that right now.

**Comment by dhowland** [comment]
okay.  too bad.
