### ISSUE TITLE
Reimplement the keymapper GUI

### ISSUE THREAD

**Issue by dhowland** [dhowland/EasyAVR#57]
The code for the keymapper is a mess.  It grew organically from a simple utility to a complex application.  There are several problems.  The code is not functionally decomposed into logical sections (spaghetti code).  The save file format is finicky and hard to use.  It looks awful because of TK.  It makes huge exe builds because of TK.

A new keymapper should be built from the ground up with wxPython.

**Comment by gorauskas** [comment]
+1

Just curious... why wxPython?

**Comment by dhowland** [comment]
Because it looks much better and it is clean and simple.  The only other real option is Qt, which requires too many libraries.  wxWidgets and wxPython were both recently rejuvenated with new releases, it makes a good time to switch.

**Comment by dhowland** [comment]
Going to call this one done.  There appears to be an issue somewhere that causes wx to crash Python, but it isn't repeatable.  Other than that I think this is done.
