### ISSUE TITLE
Hyper, Super, Meta Scancodes?

### ISSUE THREAD

**Issue by gorauskas** [dhowland/EasyAVR#58]
This is more of a question / feature request than a bug. 

I noticed that Hyper, Super, and Meta are commented out in `scancodes.py` at the bottom of the file ... I was just curious for the why and if those codes can be enabled in the near future?

**Comment by dhowland** [comment]
That's the `keysyms` table.  It translates scancodes from TK events into USB HID scancodes.  TK has codes for those keys, but USB HID code page 0x07 (keyboards) does not.
