### ISSUE TITLE
Boot Key for Teensy 2.0++

### ISSUE THREAD

**Issue by cl0rm** [dhowland/EasyAVR#72]
Is there a way to get the boot key working with the PJRC teensy bootloader?

When I press it, the teensy does indeed reboot, but not into the teensy bootloader, it seems like another boot mode which does not work correctly.

Tested with a teensy 2.0++

That might help for this:
https://www.pjrc.com/teensy/jump_to_bootloader.html

**Comment by dhowland** [comment]
It should be implemented to work correctly on Teensy, but I admit I haven't tested it in a long time.  I'll check it out.

**Comment by cl0rm** [comment]
Thank you!

I have the Teensy++2.0 (ATMEGA 1286) and it does not work. I have tested it again.
The KB disconnects, turns backlight off, but does not appear in the Teensy Loader.
With the button this works fine

**Comment by dhowland** [comment]
What keyboard are you using and what version of EasyAVR?

**Comment by cl0rm** [comment]
I am using a Gigabyte Aivia Osmium (I reverse engineered the matrix and added a teensy++2.0 myself, because the original controller died).
EasyAVR version is 2.06.02.

By the way if you want I can contribute my config files for this board, but I doubt anyone needs it, because the mod required pretty heavy SMD (de)soldering.

**Comment by dhowland** [comment]
Agreed, that config is probably not widely used enough to be needed in the default install.

I just tried my Phantom which uses a Teensy, and it works as expected.  Of course, a Teensy isn't a Teensy++ and the bootloaders are in different locations.

Let's talk about your config file.  Here is an example that uses Teensy++: https://github.com/dhowland/EasyAVR/blob/master/keymapper/easykeymap/boards/gh122.py

Notice that it includes this line:
```
import easykeymap.templates.AT90USB1286_16MHz_JUMBO as firmware
```
Does your config import a template that begins with "AT90USB1286"?

It also includes this line:
```
teensy = True
```
Does your config file have "teensy = True" ?  (capitalization matters)

**Comment by cl0rm** [comment]
yes, it does include the following lines:
teensy = True
import easykeymap.templates.AT90USB1286_16MHz_COSTAR as firmware

According to the PJRC page, Teensy++ and Teensy2.0++ use different locations

**Comment by dhowland** [comment]
Hmmm... can you share the .hex file?

**Comment by cl0rm** [comment]
yep, here you go:
[osmium_new.zip](https://github.com/dhowland/EasyAVR/files/1896358/osmium_new.zip)

**Comment by cl0rm** [comment]
[osmium.py.zip](https://github.com/dhowland/EasyAVR/files/1896363/osmium.py.zip)
this is the config file, if you need the matrix pins.
I mapped boot to fn-Numlock.
Because I mapped fn to RGUI later on through the mapper, this is the entry for the FN key in the matrix

  ((5, 4), (3, 17), 'HID_KEYBOARD_SC_RIGHT_GUI'),

**Comment by dhowland** [comment]
Whelp, I've looked at everything and it all looks perfect.  I can't explain why it isn't working.  I don't have anything with a Teensy++ 2.0 so I can't independently test it.  Not sure where to go from here.  Maybe I'll think of something in the shower.

**Comment by dhowland** [comment]
Last ditch thing to try:  try changing Teensy to False and rebuilding.

**Comment by cl0rm** [comment]
I will try that

**Comment by cl0rm** [comment]
Today I have tried teensy=False, but the behavior is exactly as before. When I press the key combo, the board disconnects, a few milliseconds later the backlight turns off, but it does not reconnect in bootloader mode. Teensy Loader does not detect it

**Comment by dhowland** [comment]
Question: when you use SCANCODE_BOOT, you said it resets, but it isn't recognized by the Teensy loader.  But, is it recognized as a keyboard, or is it just dead?

**Comment by cl0rm** [comment]
just dead. It is not recognized as anything,

**Comment by dhowland** [comment]
wow, okay that changes things.  I'm going to have to make some test builds.

**Comment by underpk** [comment]
I have the exact same problem with Teensy 2.0++, Once you press it sounds like it go into boot mode but its not.

**Comment by dhowland** [comment]
Yes this one really annoys me.  I have checked and double checked the code against the AT90USB1286 manual.  I don't have a board that uses a Teensy 2.0++, which makes it hard to investigate.  I've taken a few months off, I'll try looking again maybe something will pop out.

Are you available to run some test builds on your hardware?

**Comment by jrauch** [comment]
@dhowland I'd be happy to run test builds for you - but I'd be equally happy to send you a Teensy 2.0++ if it'd be helpful.

**Comment by TobiasWegener** [comment]
Hi everybody, I found in line 184 ` 2,` in the osmium.py file
is this supposed to be there? This looks strange to me, but maybe I am totally off here.

In general, is it possible to use a Teensy++ 2.0 or is it recommended to stick to the standard Teensy2.0?
I am planning to make a custom board I would love to use EasyAVR, that why I am looking into it.
Thank you very much, for this beautiful software.

**Comment by underpk** [comment]
> Hi everybody, I found in line 184 ` 2,` in the osmium.py file
> is this supposed to be there? This looks strange to me, but maybe I am totally off here.
> 
> In general, is it possible to use a Teensy++ 2.0 or is it recommended to stick to the standard Teensy2.0?
> I am planning to make a custom board I would love to use EasyAVR, that why I am looking into it.
> Thank you very much, for this beautiful software.

You can use it with Teensy++ 2.0 (I using it now) but I'm not sure if the software reset already solved or not.

**Comment by dhowland** [comment]
The new release v3.01.11 should fix this.
