### ISSUE TITLE
Send Mouse Buttons in Macros

### ISSUE THREAD

**Issue by sorniva** [dhowland/EasyAVR#8]
Being able to send a mouse button event in a macro would make them a lot more useful.

For one simple example, allowing the use of sending mouse button click to select a word (i.e. a double click in a text field/web page selects a 'word,' triple click generally selects a line) and then sending CTRL+C in the same macro to copy the text which becomes highlighted by the mouse button click events. .. Some sort of thing like: \Mouse1\Mouse1\CTRL(c) 

(in the above example one could simply be using their standard mouse to hover over the area they want to select, for this usage example mouse movement events in a macro wouldn't be required)  

At the moment it doesn't seem sending a mouse button click event is possible, if there is any way we could get there it'd be great.

**Comment by dhowland** [comment]
Unfortunately this isn't possible with the architecture of macros in EasyAVR.  You may want to simply use CTRL+arrow keys or CTRL+a
