### ISSUE TITLE
Python error when opening JSON files

### ISSUE THREAD

**Issue by MiLeG** [dhowland/EasyAVR#86]
I have tried loading a json file generated from [KLE](http://www.keyboard-layout-editor.com) and i am getting a python error like this:
![error easy avr](https://user-images.githubusercontent.com/19146713/42462288-1e0d9c5e-83a3-11e8-98a8-44774cda694c.png)

I have tried downloading a .dat layout and a similair error appears. When i downloaded the v2.06.02 version, the .dat file was loaded perfectly.

**Comment by dhowland** [comment]
Hi thanks for helping out the project!  Is it possible to share the file that caused the error?

**Comment by MiLeG** [comment]
Sure, I have tried out several JSONs, all with similair or same results.


[JSONs.zip](https://github.com/dhowland/EasyAVR/files/2177137/JSONs.zip)

**Comment by dhowland** [comment]
Wait, wait.  Are you trying to open KLE layouts using File->Open ?

That doesn't work.  You can only open EasyAVR save files that way.  To use KLE layouts, you have to use the wizard.
