### ISSUE TITLE
Assigning F13 - F24 results in no output of any scancodes.

### ISSUE THREAD

**Issue by sorniva** [dhowland/EasyAVR#9]
Using v2.03.01 it seems trying to run a layout with F13-24 results in those keys sending no scancodes for the keys mapped to F13-24

Running evtest in linux results in no scancodes being shown when pressing F13-24.

Running wireshark to scan USB traffic shows nothing at all being sent from the board when pressing keys bound to F13-24.

Everything else works as expected.

One other individual reported being able to reproduce this.

**Comment by dhowland** [comment]
This is because the NKRO field is not large enough to encode those scancodes.  They do not appear on a normal Windows keyboard page.  If you need them to work, try disabling NKRO.
