### ISSUE TITLE
Feature request: Mod one time only.

### ISSUE THREAD

**Issue by RuanoK** [dhowland/EasyAVR#94]
Feature request: Mod one time only.

 I want to press the "shift" key once and release it, then press a normal key and
run in capital letter only that first time.

Thank you in avance.

**Comment by dhowland** [comment]
Yes this was asked on [geekhack](https://geekhack.org/index.php?topic=51252.2500) too.  I think it's a good idea.  I gave it some cursory thought and I think basic sticky keys should be doable without a huge impact to memory usage (memory usage is the main constraining factor on this project)

**Comment by dhowland** [comment]
I have implemented this feature.  A few more days of testing and it will show up in the repo.

**Comment by dhowland** [comment]
tested, seems to be working
